### PR TITLE
UPM support

### PR DESCRIPTION
**Pull request by bilal-arikan**
## What changed?

_Describe the changes you have made to improve this project._
I moved the editor folders,
created Assembly Definitons,
created package.json,
made changes to the path values, to be able to generate scripts and manifest files.

I haven't tried it in a real project yet.

_Closed issues._

### CODE REVIEW

**Comment by jizc** [comment]
This looks interesting! Thanks for contributing, however I very rarely work on this anymore, so it may be a while before I can review this properly.

**Comment by dglwilkins** [comment]
Any update on when this will get reviewed and pulled?

**Comment by bilal-arikan** [comment]
Hi,
The repository I forked seems to be working fine. I am going to release an
update with CloudOnce for cloud save features of this game "
https://play.google.com/store/apps/details?id=com.arikan.realdriver" soon.
If I encounter errors, I will share them with you.

Dan Wilkins ***@***.***>, 7 May 2022 Cmt, 13:35 tarihinde
şunu yazdı:

**Comment by bilal-arikan** [comment]
Hi,
I found a bug.

>
>
>
>
>
>
>
>
>
>
>
>
>
> *"{   "TermsAccepted": "true",   "Days": "[738290,738293,738294]",
>  "LocalSaveTime": "\"0001-01-01T00:00:00\"",   "LFCO":
> "\"2022-05-16T12:51:59.7759458Z\"",   "LACO":
> "\"2022-05-16T12:52:02.5090104Z\"",   "Money": "33500",   "Cars":
> "[\"Honda_Civic\",\"M4\",\"A180\"]",   "FreeGifts": "[]",   "Firsts":
> "[\"FirstGameOpen\",\"FirstGamePlay\"]",   "Levels":
> "[\"Tutorial\",\"GrassHills_Race_00\",\"GrassHills_TimeAttack_00\",\"GrassHills_CleanDrive_00\",\"GrassHills_Drift_00\"]",
>  "PassedLevels": "[]",   "LastSaveTime": "01.January.0001 00:00:00"}"*

After saving this data in CloudString, when I load the data again, I read
it like this.

>
> *"}"*

  the type of my data is Dictionary<string, string> . but Values are also
different strings of Json values.

Bilal Arikan ***@***.***>, 13 May 2022 Cum, 15:38 tarihinde
şunu yazdı:

**Comment by jizc** [comment]
I've started work on refactoring the entire project, where I'm also looking at supporting UPM. This PR won't work with that, but it has been helpful in deciding how to structure the project going forward.

So I'm going to close this, but thank you for the suggestion, as it's what inspired me to work on this a bit again 😊

It may still be a while before I release anything new though.

**Comment by HybridShivam** [comment]
Any updates on the UPM support?
Thanks!

**Comment by jizc** [comment]
I ultimately decided that UPM is out of scope for CloudOnce. Maybe @bilal-arikan can update their fork to v3.1.0.

**Comment by HybridShivam** [comment]
@jizc Thanks for the quick response.
I just wanted to ask, If I install the latest `UPM` packages for:
1. EDM4U
2. Google Play Games

and while installing `CloudOnce-v3.1.0.unitypackage` uncheck everything except `Extensions\Cloudonce`
Will it work?
I am currently trying that but running into some issues.

**Comment by jizc** [comment]
I would try to import CloudOnce into an empty project first, then move over everything but EDM4U and Google Play Games. There still may be some issues though.

**Pull request closed without merging**
