### PR TITLE
Restrict MenuLinks to be compiled in editor only

### PR DESCRIPTION
**Pull request by ondrowan**
## What changed?

_Describe the changes you have made to improve this project._

This issue seemed to prevent iOS or Android builds since it also included editor script in project.

### CODE REVIEW

**Comment by jizc** [comment]
Hi @ondrowan,

Thank you for submitting a PR. But I don't see why this change is necessary. Code placed inside `Editor` folders are not included in builds, so the `#if UNITY_EDITOR` should be redundant.

I have built iOS and Android builds with no issues, and I've not heard of anyone else experiencing this either. If you are certain that this change is what fixed an issue you had, please provide a repository that demonstrates it. It would also be helpful to know what version of Unity you are running, and what specific type of build causes the issue.

**Comment by ondrowan** [comment]
I just tried it in a clean repo and you're right. It works well, but only if I'm not using assembly definitions. With assembly definitions it gives me the following error once I try to build iOS version:

> Assets\Extensions\CloudOnce\Internal\Editor\MenuLinks.cs(16,10): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)

Here's a repo to reproduce it: https://github.com/ondrowan/cloud-once-repro It was created using Unity 2018.4.10f, but I guess any 2018.4 version will do.

This patch fixed this issue, but I don't really know if it's a right way to do it or if I just misunderstand something regarding assembly definitions. If I understand it correctly, assembly definition for `CloudOnce` creates a dynamic library with all of its files. Since `MenuLinks.cs` requires a namespace that's available only if I'm using editor, the iOS build fails. So one option is to use `#if` directive, which seemed to be the easiest solution. Another is to create an assembly definition with restricted platforms for each of the folders in `CloudOnce`, but I don't know if it's even possible with the current structure of the project. I gave it some time, but it seems I always hit a wall with certain folders / files.

**Comment by jizc** [comment]
Thank you for the details and the demo repo, I'll try to find the time to look at it tomorrow.

**Comment by jizc** [comment]
Checked it out now, and I agree with your solution 🎉

Thanks again for taking the time to submit the PR and following up with additional info.

**Pull request merged**
